# Fixtures needed for puppetlabs_spec_helper
fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.3.2'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.1.1'
    datacat:
      repo: 'richardc/datacat'
      ref: '0.6.1'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '1.1.4'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '1.1.3'
    ntp:
      repo: 'puppetlabs/ntp'
      ref: '3.2.1'
    apt:
      repo: 'puppetlabs/apt'
      ref: '1.6.0'
    mcollective:
      repo: 'puppetlabs/mcollective'
      ref: '2.0.0'
    shellshock:
      repo: 'renanvicente/shellshock'
      ref: '0.0.2'
    ssh:
      repo: 'saz/ssh'
      ref: '2.4.0'

# Setting up a couple of symlinks to make it easier to treat profiles and roles
# just as another set of "modules" in our environment
  symlinks:
    profile: "#{source_dir}/dist/profile"
    role: "#{source_dir}/dist/role"
