forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/stdlib', '4.3.2'
mod 'puppetlabs/apt', '1.6.0'
mod 'puppetlabs/ntp', '3.2.1'
mod 'puppetlabs/firewall', '1.1.3'
mod 'puppetlabs/mcollective', '2.0.0'
mod 'puppetlabs/concat', '1.1.1'
mod 'richardc/datacat', '0.6.1'
mod 'puppetlabs/inifile', '1.1.4'
mod 'saz/ssh', '2.4.0'

mod 'renanvicente/shellshock', '0.0.2'
