require 'puppet-lint'
require 'puppetlabs_spec_helper/rake_tasks'

desc "Validate the Puppet syntax of all manifests"
task :validate do
  Dir['./{dist,manifests}/**/*.pp'].each do |filename|
    sh "puppet parser validate '#{filename}'"
  end
end

desc 'Run puppet-lint on Puppet manifests defined in this repo'
task :lint do
  require 'puppet-lint/tasks/puppet-lint'

  PuppetLint.configuration.send('disable_80chars')
  PuppetLint.configuration.send('disable_class_parameter_defaults')
  PuppetLint.configuration.send('disable_names_containing_dash')
  PuppetLint.configuration.ignore_paths = ['modules/**/*.pp', 'spec/fixtures/**/*.pp', 'vendor/**/*.pp']
  PuppetLint.configuration.fail_on_warnings = true
end
