Vagrant.require_version ">=1.6.0"
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  access_key_id = ENV['AWS_ACCESS_KEY']
  secret_access_key = ENV['AWS_SECRET_KEY']
  keypair = ENV['AWS_KEYPAIR_NAME']

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = access_key_id
    aws.secret_access_key = secret_access_key
    aws.keypair_name = keypair

    aws.region = "us-east-1"

    aws.ami = "ami-9eaa1cf6"
    aws.instance_type = "t2.medium"

    aws.associate_public_ip = true
    aws.subnet_id = "subnet-4acd2513"
    aws.private_ip_address = "10.0.0.10"

    aws.instance_ready_timeout = 240

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/home/phil/.ssh/id_rsa"
  end

  config.vm.provision "shell", path: "https://gist.githubusercontent.com/pcfens/42fefc77a64461f3384d/raw/fe13849aa2c8bb87f0c8ee00b9161949b60d59b8/install_puppet.sh"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file = "site.pp"
    puppet.options = [
      "--pluginsync"
    ]
  end
end
