forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/inifile'
mod 'puppetlabs/mcollective'
mod 'puppetlabs/rabbitmq'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/puppetdb',
  :git => 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'

mod 'theforeman/foreman'
mod 'jfryman/nginx', '0.0.10'
